ISPP-G-8/infantem

- src/main/java/com/isppG8/infantem/infantem/sueño/Sueño.java
- src/main/java/com/isppG8/infantem/infantem/sueño/SueñoController.java
- src/main/java/com/isppG8/infantem/infantem/sueño/SueñoRepository.java
- src/main/java/com/isppG8/infantem/infantem/sueño/SueñoService.java
- src/main/java/com/isppG8/infantem/infantem/sueño/tipoSueño.java
Se crea todo lo relacionado con la clase Sueño así como funciones de CRUD
> Clase Sueño

- src/main/java/com/isppG8/infantem/usuario/Usuario.java
- src/main/java/com/isppG8/infantem/usuario/UsuarioController.java
- src/main/java/com/isppG8/infantem/usuario/UsuarioRepository.java
- src/main/java/com/isppG8/infantem/usuario/UsuarioService.java
> #34 Usuarios

- populate_database/populate_database.sql
- src/main/java/com/isppG8/infantem/infantem/allergen/Allergen.java
- src/main/java/com/isppG8/infantem/infantem/exceptions/ErrorMessage.java
- src/main/java/com/isppG8/infantem/infantem/exceptions/ExceptonHandleController.java
- src/main/java/com/isppG8/infantem/infantem/exceptions/ResourceNotFoundException.java
- src/main/java/com/isppG8/infantem/infantem/foodNutrient/FoodNutrient.java
- src/main/java/com/isppG8/infantem/infantem/intake/Intake.java
- src/main/java/com/isppG8/infantem/infantem/recipe/Recipe.java
- src/main/java/com/isppG8/infantem/infantem/recipe/RecipeController.java
- src/main/java/com/isppG8/infantem/infantem/recipe/RecipeRepository.java
- src/main/java/com/isppG8/infantem/infantem/recipe/RecipeService.java
- src/main/java/com/isppG8/infantem/infantem/user/User.java
- src/test/java/com/isppG8/infantem/infantem/recipe/RecipeServiceTest.java
Se ha cambiado la logica tras la entidad Recipes del backend para adaptarla al nuevo UML. También se añade lógica de exceptiones.
> Feat recipe recommendation Ref #52

- src/main/java/com/isppG8/infantem/infantem/user/UserService.java
Cambios:
- Ya no se modifica la contraseña al hacer un update de user
> fix: No longer set password in user update

- frontend/app/(tabs)/account/index.tsx
- frontend/app/(tabs)/recipes/index.tsx
- frontend/app/index.tsx
- frontend/context/AuthContext.tsx
- frontend/package-lock.json
- frontend/types/AuthContextType.ts
- frontend/types/User.ts
He eliminado la autenticación en recipes y en account ya que no era necesaria, ahora se usa el hook de AuthContext.tsx
> fix: updated auth on account and recipes

- .github/workflows/codacy.yml
Se ha añadido un flujo de trabajo de GitHub Actions para integrar Codacy en el proceso de CI/CD. Este flujo realiza un análisis de seguridad y calidad del código en cada `push` y `pull request` a la rama `main`.
> feat: añadir flujo de trabajo de Codacy 

- src/main/resources/application-development.properties
Corrige una línea en la configuración del application.properties del perfil de desarrollo para que pueda conectarse correctamente a la base de datos.
> fix: Add dialect for DB in development profile

- frontend/context/AuthContext.tsx
Fix issue where users were incorrectly redirected to the sign-in page when refreshing (Ctrl+R) any screen while already authenticated. 
In this PR, we separate token retrieval from validation and using a dedicated effect hook to properly update authentication state when token changes. Now users remain on their current page when refreshing while logged in.
> Remove unnecessary redirect to sign-in screen

- frontend/app/(tabs)/baby/index.tsx
First, I added the titles on top of the labels; nothing much to explain there.
Second, I fixed the error that wouldn’t let you modify a float number in the form.
What was the issue? Every time the value changed, it was being parsed as a float. But when you typed a "." or a ",", it got converted to an integer instead, like this:
x. → x
To fix it, I made a copy of the baby object where all values are stored as strings. Then, when submitting the data, they get parsed into the correct type.
I also noticed another problem: the baby object we fetch isn’t a DTO, so it comes with a bunch of unnecessary relationships that the backend expects when updating. Until the backend returns a proper DTO instead of the full entity, I’ll need to keep working with a copied version of the baby object.
> fix: Fix floating point numbers on Baby Closes #235

- frontend/app/(tabs)/_layout.tsx
> Switch baby and account positions and modify the baby icon 

- src/main/java/com/isppG8/infantem/infantem/auth/AuthController.java
- src/main/java/com/isppG8/infantem/infantem/auth/dto/AuthDTO.java
Auth/me returned a massive json, changed it to a DTO with only the basic information; request changes if anything's missing
> fix: made DTO for auth/me endpoint

- frontend/components/TermsConditionsModal.tsx
Correct terms and conditions and add SLA  Closes #297
> Correct terms and conditions and add SLA

- frontend/app/(tabs)/_layout.tsx
- frontend/app/(tabs)/account/subscriptionweb.tsx
- frontend/context/AuthContext.tsx
- frontend/static/styles/globalStyles.ts
- src/main/java/com/isppG8/infantem/infantem/baby/Baby.java
- src/main/java/com/isppG8/infantem/infantem/baby/dto/BabyDTO.java
Cambios propuestos por los usuarios piloto. Algunos cambios están en proceso de ser corregidos, aún no se han subido
> Feat: UP improvements

- src/main/java/com/isppG8/infantem/infantem/recipe/RecipeController.java
- src/main/java/com/isppG8/infantem/infantem/recipe/RecipeRepository.java
- src/main/java/com/isppG8/infantem/infantem/recipe/RecipeService.java
- src/test/java/com/isppG8/infantem/infantem/recipe/RecipeControllerTest.java
- src/test/java/com/isppG8/infantem/infantem/recipe/RecipeServiceTest.java
Add recipe filters by name requested by @santos-404
> Feat:Recipe name filter

- src/test/java/com/isppG8/infantem/infantem/dream/DreamControllerTest.java
- src/test/java/com/isppG8/infantem/infantem/dream/DreamServiceTest.java
Unit tests have been implemented for the Dream entity at the service and controller levels. The tests include:
DreamService: Tests to verify the creation, update, retrieval, and deletion of dreams.
DreamController: Tests to ensure the controller routes function correctly, including parameter validation and appropriate response returns.
Closes #311 : Implement tests for the service and controller of the Dream entity.
All tests related to the Dream service and controller have been executed and passed successfully.
> feat: Implement unit tests for Dream service and controller [Closes #311]

- src/main/resources/application-test.properties
- src/main/resources/test_data.sql
Nota: El workflow de test no lo pasa debido a que se ha aceptado anteriormente una pull request sin que pasen los tests :(
> feat: Add test populator

- README.md
- docs/Setup-Project.md
He cambiado el readme, ahora es más descriptivo sobre el proyecto
> new Readme

- frontend/app/(tabs)/allergens/index.tsx
- src/main/resources/data.sql
Show message in allergens if user does not have babies and add some babies to data.sql
> feat: show message in allergens if user does not have babies

- frontend/app/(tabs)/marketplace/index.tsx
- frontend/app/(tabs)/recipes/detail.tsx
- frontend/components/MarketItem.tsx
- frontend/types/Recipe.ts
Edit and delete recipes, also fixed some styles in the marketplace
> Edit and delete recipes

- frontend/app/(tabs)/baby/index.tsx
Show allergens of every baby in babies. Add also some test data to data.sql
> feat: show allergens of every baby in babies Ref # 289

- frontend/components/TermsConditionsModal.tsx
Fix SLA with Claudette, although it is useless at this point
> Fix SLA with Claudette

- src/main/java/com/isppG8/infantem/infantem/question/Question.java
You can now delete entries with associated questions.
> Delete intake with associated questions

- .github/workflows/sonarqube.yml
Change sonar workflow database
> fix: fix sonar workflow
